<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'آدرس',
    'Are you sure you want to delete this item?' => 'مطمئنید که میخواهید این آیتم را حذف کنید',
    'Birthday' => 'سال تولد',
    'Birthplace' => 'محل تولد',
    'Capacity' => 'ظرفیت',
    'Cellphone' => 'تلفن همراه',
    'Certificate' => 'مدرک',
    'Cid' => 'نام استاد',
    'Cname' => 'نام استاد',
    'Cost' => 'هزینه کلاس',
    'Courses' => 'درس ها',
    'Create Course' => 'درس جدید',
    'Create Payment' => 'پرداخت جدید',
    'Create Register' => 'ثبت نام جدید',
    'Create Student' => 'دانشجو جدید',
    'Create Teacher' => 'استاد جدید',
    'Delete' => 'حذف',
    'Enddate' => 'تاریخ پایان',
    'Endtime' => 'زمان پایان',
    'Experience' => 'تجربه',
    'Fname' => 'نام',
    'ID' => '',
    'Lname' => 'نام خانوادگی',
    'Payments' => 'پرداخت ها',
    'Pdate' => 'تاریخ پرداخت',
    'Phone' => 'تلفن',
    'Rdate' => 'تاریخ ثبت نام',
    'Registers' => 'ثبت نام',
    'Reset' => 'مجدد',
    'Save' => 'ذخیره',
    'Search' => 'جست و جو',
    'Sid' => 'نام دانشجو',
    'Startdate' => 'تاریخ شروع',
    'Starttime' => 'زمان شروع',
    'Students' => 'دانشجویان',
    'Teachers' => 'استاد ها',
    'The requested page does not exist.' => 'صفحه مورد نظر در دسترس نیست',
    'Tid' => 'نام استاد',
    'Update' => 'ویرایش',
    'Update Course: mode' => '',
    'Update Payment: mode' => '',
    'Update Register: mode' => '',
    'Update Student: mode' => '',
    'Update Teacher: mode' => '',
    'Workfield' => 'حرفه',
];
